#!/bin/bash

cd "${HOME}"

echo -e  "Executando, a linha:\n\n  ${@}\n"

echo -E "${@}" | bash

echo -e "\nO comando terminou com saída '${?}'\n"
read -n1 -p "Pressione qualquer tecla para fechar..." dummy
