#!/bin/bash

function getExpression(){
  original_expression=$(yad --form --title='Calculadora de linha' \
                 --text="<big><b>Digite uma expressão e pressione Enter para obter o resultado</b></big>\nExemplo: 2+2x(3+7)\n" \
                 --columns=1 --width=480 --field='':EDT "${result}" --field=' ':LBL --button=gtk-cancel:1 --button="=":0 \
                 --borders=32 --fixed --center)
  [ ! "${?}" = "0" ] && exit 0
  calculation
}
                 
function calculation(){
  original_expression=$(echo ${original_expression} | sed 's|\|\|||g;')
  expression=$(echo ${original_expression} | sed 's|[xX]|*|g;s|{|(|g;s|}|)|g;s|\[|(|g;s|\]|)|g')
  result="${original_expression} = "$(echo ${expression} | bc)
  getExpression
}

original_expression=${@}

[ "${original_expression}" = "" ] && {
  getExpression
}

calculation

